export const Traits = [
    { Title: "BodyHair",
        Help: "Body hair help",
        Options: [
        { Desc: "None", Num: "1" },
        { Desc: "Some", Num: "2" },
        { Desc: "More", Num: "3" },
        { Desc: "A Lot", Num: "4" },
    ]},
    { Title: "BodyProportions",
        Help: "Body proportion help",
        Options: [
        { Desc: "Rectangle", Num: "01" },
        { Desc: "Triangle/Pear", Num: "02" },
        { Desc: "Spoon", Num: "03" },
        { Desc: "Hourglass", Num: "04" },
        { Desc: "Top Hourglass", Num: "05" },
        { Desc: "Bottom Hourglass", Num: "06" },
        { Desc: "Inverted Triangle/Apple", Num: "07" },
        { Desc: "Round", Num: "08" },
        { Desc: "Diamond", Num: "09" },
        { Desc: "Athletic", Num: "10" },
    ]},
    { Title: "BustSize",
        Help: "Bust size help",
        Options: [
        { Desc: "Flat", Num: "1" },
        { Desc: "Rounded", Num: "2" },
        { Desc: "Small", Num: "3" },
        { Desc: "Average", Num: "4" },
        { Desc: "Large", Num: "5" },
        { Desc: "Larger", Num: "6" },
    ]},
    { Title: "FaceShape",
        Help: "Facial shape help",
        Options: [
        { Desc: "Triangle", Num: "1" },
        { Desc: "Round", Num: "2" },
        { Desc: "Square", Num: "3" },
        { Desc: "Oval", Num: "4" },
        { Desc: "Diamond", Num: "5" },
        { Desc: "Rectangle", Num: "6" },
        { Desc: "Heart", Num: "7" },
    ]},
    { Title: "FacialHair",
        Help: "Facial hair help",
        Options: [
        { Desc: "None", Num: "1" },
        { Desc: "Stubble", Num: "2" },
        { Desc: "A Little", Num: "3" },
        { Desc: "More", Num: "4" },
        { Desc: "A Lot", Num: "5" },
    ]},
    { Title: "MuscleTone",
        Help: "Muscle tone help",
        Options: [
        { Desc: "Soft", Num: "1" },
        { Desc: "Firm", Num: "2" },
        { Desc: "Very Firm", Num: "3" },
    ]},
    { Title: "Weight",
        Help: "Weight help",
        Options: [
        { Desc: "Very Small", Num: "1" },
        { Desc: "Small", Num: "2" },
        { Desc: "Average", Num: "3" },
        { Desc: "Big", Num: "4" },
        { Desc: "Bigger", Num: "5" },
    ]},
];